### ISSUE TITLE
Can't view all pdf objects

### ISSUE THREAD

**Issue by 50u1w4y** [dzzie/pdfstreamdumper#1]
Hello, dzzie. Thank you for the awesome software.

Recently, I found this software can't parse all objects in a pdf document. I upload a hello pdf as an example, here is the [link](https://github.com/50u1w4y/NetDisk/blob/master/hello-world.pdf).

In the object 2, we can see here is an object 8 which represents an image. However, in the objects viewer list, we can't see the object 8.

I'm not sure if this is a bug, or only I forget to choose some buttom, or it's right that the software doesn't show the object because it is unrelated to malicious behavior.

If it is right, can I request a feature to show? Because the software is good at parsing pdf documents, not only analyze malicious pdf documents.

**Comment by dzzie** [comment]
Hi, the stream is not showing up in the main list to the left because there was an error decompressing the stream.

It does show up in the lower listview, on the errors tab. If you click there you will see the stream raw data. If you then right click on the list entry and choose Load as Image you will be able to view the image. You can also right click to View raw object to see the raw header data. 

If you goto tools Manual Filters you can see what filters are implemented and test run on them streams. DCTDecode filter is not implemented. I am not sure what we would gain by implementing it since the image is viewable when using Load as Image.

**Comment by 50u1w4y** [comment]
Thank you very much for your response, I've understood that.
